/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MMemberTokenRouteImport } from './routes/m.$memberToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MMemberTokenRoute = MMemberTokenRouteImport.update({
  id: '/m/$memberToken',
  path: '/m/$memberToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m/$memberToken': typeof MMemberTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/m/$memberToken': typeof MMemberTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m/$memberToken': typeof MMemberTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/m/$memberToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/m/$memberToken'
  id: '__root__' | '/' | '/m/$memberToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MMemberTokenRoute: typeof MMemberTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$memberToken': {
      id: '/m/$memberToken'
      path: '/m/$memberToken'
      fullPath: '/m/$memberToken'
      preLoaderRoute: typeof MMemberTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MMemberTokenRoute: MMemberTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
