/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MMemberTokenRouteImport } from './routes/m.$memberToken'
import { Route as LLeaderTokenRouteImport } from './routes/l.$leaderToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MMemberTokenRoute = MMemberTokenRouteImport.update({
  id: '/m/$memberToken',
  path: '/m/$memberToken',
  getParentRoute: () => rootRouteImport,
} as any)
const LLeaderTokenRoute = LLeaderTokenRouteImport.update({
  id: '/l/$leaderToken',
  path: '/l/$leaderToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/l/$leaderToken': typeof LLeaderTokenRoute
  '/m/$memberToken': typeof MMemberTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/l/$leaderToken': typeof LLeaderTokenRoute
  '/m/$memberToken': typeof MMemberTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/l/$leaderToken': typeof LLeaderTokenRoute
  '/m/$memberToken': typeof MMemberTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/l/$leaderToken' | '/m/$memberToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/l/$leaderToken' | '/m/$memberToken'
  id: '__root__' | '/' | '/l/$leaderToken' | '/m/$memberToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LLeaderTokenRoute: typeof LLeaderTokenRoute
  MMemberTokenRoute: typeof MMemberTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$memberToken': {
      id: '/m/$memberToken'
      path: '/m/$memberToken'
      fullPath: '/m/$memberToken'
      preLoaderRoute: typeof MMemberTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$leaderToken': {
      id: '/l/$leaderToken'
      path: '/l/$leaderToken'
      fullPath: '/l/$leaderToken'
      preLoaderRoute: typeof LLeaderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LLeaderTokenRoute: LLeaderTokenRoute,
  MMemberTokenRoute: MMemberTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
